CREATE DATABASE ussr_rust_server_db;
GRANT ALL ON ussr_rust_server_db.* TO ussr_rust_db_user@localhost IDENTIFIED BY '';
FLUSH PRIVILEGES;
USE ussr_rust_server_db;
CREATE TABLE billing_table (id int NOT NULL AUTO_INCREMENT, User varchar(50) NOT NULL, Item varchar(50) NOT NULL, Quantity int NOT NULL, Pay_amount int NOT NULL, isDispensed tinyint(1), PRIMARY KEY (id));
CREATE TABLE billing_table_costs (id int NOT NULL AUTO_INCREMENT, Item varchar(50) NOT NULL, Cost int NOT NULL, PRIMARY KEY (id));
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_ak47", 400);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_bolt", 600);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_crossbow", 20);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_csmg", 300);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_db", 150);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_eoka", 70);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_legolas", 10);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_pump_shotgun", 150);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_checkist", 100);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_pistol", 110);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_dmr", 350);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_thompson", 250);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_waterpipe", 70);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_holo", 100);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_4x", 300);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_boost", 400);
INSERT INTO billing_table_costs (Item, Cost) VALUES ("wpn_brake", 100);
